version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword_123"
      ACCEPT_EULA: "Y"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: